commodities_data = {
    "Aggregate": {
        "url": "https://fred.stlouisfed.org/series/WPS1321",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Argon": {
        "url": "https://fred.stlouisfed.org/series/PCU325120325120C",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Cement": {
        "url": "https://fred.stlouisfed.org/series/PCU32733273",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Electronics": {
        "url": "https://fred.stlouisfed.org/series/PCU334334",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Ethanol": {
        "url": "https://fred.stlouisfed.org/series/WPU06140341",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Fibre Glass": {
        "url": "https://fred.stlouisfed.org/series/PCU326199326199A",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Glue": {
        "url": "https://fred.stlouisfed.org/series/PCU325520325520P",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Granite": {
        "url": "https://fred.stlouisfed.org/series/PCU3279913279911",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Gypsum": {
        "url": "https://fred.stlouisfed.org/series/PCU3274203274201",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Limestone": {
        "url": "https://fred.stlouisfed.org/series/PCU2123122123120",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Marble": {
        "url": "https://fred.stlouisfed.org/series/PCU3279913279917",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Metal": {
        "url": "https://fred.stlouisfed.org/series/PMETAINDEXM",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Mineral Wool": {
        "url": "https://fred.stlouisfed.org/series/PCU3279933279934",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Nylon": {
        "url": "https://fred.stlouisfed.org/series/WPU031",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Organic Chemical": {
        "url": "https://fred.stlouisfed.org/series/WPU0614",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Paper": {
        "url": "https://fred.stlouisfed.org/series/WPU0911",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Stainless Steel": {
        "url": "https://fred.stlouisfed.org/series/WPU10170674",
        "source": "FRED",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Chromium": {
        "url": "https://www.investing.com/commodities/chromium-99-min-china-futures",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "CNY",
    },
    "Kraft Pulp": {
        "url": "https://uk.investing.com/commodities/shfe-bleached-softwood-kraft-pulp-futures-historical-data",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "CNY",
    },
    "Lithium": {
        "url": "https://uk.investing.com/commodities/lithium-carbonate-99.5-min-china-futures",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "CNY",
    },
    "Lumber": {
        "url": "https://uk.investing.com/commodities/lumber-historical-data",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "USD",
    },
    "Palladium": {
        "url": "https://uk.investing.com/commodities/palladium-historical-data",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "USD",
    },
    "Polyethylene": {
        "url": "https://uk.investing.com/commodities/lldpe-futures-historical-data",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "CNY",
    },
    "Polypropylene": {
        "url": "https://uk.investing.com/commodities/pp-futures",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "CNY",
    },
    "Polyvinyl": {
        "url": "https://uk.investing.com/commodities/pvc-com-futures-historical-data",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "CNY",
    },
    "Rubber": {
        "url": "https://www.investing.com/commodities/rubber-tsr20-futures-historical-data",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "USD",
    },
    "Steel": {
        "url": "https://uk.investing.com/commodities/steel-rebar",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "USD",
    },
    "Steel Scrap": {
        "url": "https://uk.investing.com/commodities/steel-scrap",
        "source": "Investing.com",
        "frequency": "Live",
        "update": "Live",
        "currency": "USD",
    },
    "Chemical": {
        "url": "https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/gax4/ppi",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Clay": {
        "url": "https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/g32g/ppi",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Construction labour UK": {
        "url": "https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/timeseries/k5ah/emp",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Glass": {
        "url": "https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/g32e/ppi",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Inflation UK": {
        "url": "https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/l55o/mm23",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "%",
    },
    "Labour UK": {
        "url": "https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/averageweeklyearningsingreatbritain/latest",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "GBP",
    },
    "Other": {
        "url": "https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/producerpriceinflation/june2024includingservicesapriltojune2024",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Water": {
        "url": "https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/dobs/mm23",
        "source": "ONS",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Aluminium": {
        "url": "https://tradingeconomics.com/commodity/aluminum",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-lmahds03",
        "currency": "USD",
    },
    "Coal": {
        "url": "https://tradingeconomics.com/commodity/coal",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-xal1",
        "currency": "USD",
    },
    "Cobalt": {
        "url": "https://tradingeconomics.com/commodity/cobalt",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-lco1",
        "currency": "USD",
    },
    "Construction activity UK": {
        "url": "https://www.investing.com/economic-calendar/construction-pmi-44",
        "source": "Investing.com v2",
        "frequency": "Monthly",
        "update": "7w",
        "currency": "Index",
    },
    "Containerized Freight China-Europe": {
        "url": "https://tradingeconomics.com/commodity/containerized-freight-index",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-spscfi",
        "currency": "USD",
    },
    "Copper": {
        "url": "https://tradingeconomics.com/commodity/copper",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-hg1",
        "currency": "USD",
    },
    "Cotton": {
        "url": "https://tradingeconomics.com/commodity/cotton",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id":"Label-ct1",
        "currency": "USD",
    },
    "Crude Oil": {
        "url": "https://tradingeconomics.com/commodity/crude-oil",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id":"Label-cl1",
        "currency": "USD",

    },
    "Electricity UK": {
        "url": "https://tradingeconomics.com/united-kingdom/electricity-price",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-gbrelepri",
        "currency": "GBP",
    },
    "EU Carbon Permits": {
        "url": "https://tradingeconomics.com/commodity/carbon",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-eecxm",
        "currency": "EUR",
    },
    "Gold": {
        "url": "https://tradingeconomics.com/commodity/gold",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-xauusd",
        "currency": "USD",
    },
    "Iron Ore": {
        "url": "https://tradingeconomics.com/commodity/iron-ore",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-sco",
        "currency": "USD",
    },
    "Lead": {
        "url": "https://tradingeconomics.com/commodity/lead",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-ll1",
        "currency": "USD",
    },
    "Natural Gas": {
        "url": "https://tradingeconomics.com/commodity/natural-gas",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-ng1",
        "currency": "USD",
    },
    "Nickel": {
        "url": "https://tradingeconomics.com/commodity/nickel",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-ln1",
        "currency": "USD",
    },
    "Silver": {
        "url": "https://tradingeconomics.com/commodity/silver",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-xagusd",
        "currency": "USD",
    },
    "Tin": {
        "url": "https://tradingeconomics.com/commodity/tin",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-lmsnds03",
        "currency": "USD",
    },
    "Zinc": {
        "url": "https://tradingeconomics.com/commodity/zinc",
        "source": "Trading Economics",
        "frequency": "Live",
        "update": "Live",
        "element_id": "Label-lmzsds03",
        "currency": "USD",
    }
}