# Generated by Django 5.0.6 on 2024-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
