# Generated by Django 5.0.6 on 2024-09-08 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_manufacturer_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityproduction',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.commodity'),
        ),
        migrations.AlterField(
            model_name='materialproportion',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_proportions', to='main.commodity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('unique_commodities_count', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('increasefromlastyear', models.FloatField(blank=True, null=True)),
                ('commodities', models.ManyToManyField(blank=True, related_name='projects', to='main.commodity')),
                ('products', models.ManyToManyField(blank=True, related_name='projects', to='main.product')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_projects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='view',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
