# Generated by Django 5.0.6 on 2024-09-08 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='commodities',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='main.commodity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='main.product'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
