# Generated by Django 5.0.6 on 2024-09-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_notification_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='new',
        ),
        migrations.AddField(
            model_name='notification',
            name='seen_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='seen_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
