# Generated by Django 5.0.6 on 2024-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_notification_new_notification_seen_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='activated_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
