# Generated by Django 5.0.6 on 2024-09-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_view_user_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='hidden_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
