# Generated by Django 5.0.6 on 2024-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'permissions': [('lite', 'Lite Perm'), ('standard', 'Standard Perm'), ('unlimited', 'Unlimited Perm')],
            },
        ),
    ]
