# Generated by Django 5.0.6 on 2024-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_usersubscription_timestamp_usersubscription_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(default='gbp', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='interval',
            field=models.CharField(default='month', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
