# Generated by Django 5.0.6 on 2024-10-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_usersubscription_currency_usersubscription_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
        ),
    ]
