# Generated by Django 5.0.6 on 2024-10-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price_history_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price_history_source',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price_source',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='production_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='production_source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='production_unit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
