# Generated by Django 5.0.6 on 2024-10-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_commodity_price_history_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pcr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
