# Generated by Django 5.0.6 on 2024-10-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
