# Generated by Django 5.0.6 on 2024-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_product_product_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
