# Generated by Django 5.0.6 on 2024-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_product_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='production_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
