# Generated by Django 5.0.6 on 2024-10-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_commodity_production_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commodityprice',
            unique_together={('commodity', 'currency', 'date')},
        ),
    ]
