# Generated by Django 5.0.6 on 2024-10-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_commodityprice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commodityprice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='commodityprice',
            constraint=models.UniqueConstraint(fields=('commodity', 'currency', 'date'), name='unique_commodity_currency_date'),
        ),
    ]
