# Generated by Django 5.0.6 on 2024-10-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_product_first_man_image_format_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='first_prod_image_format',
            new_name='image_format',
        ),
    ]
