# Generated by Django 5.0.6 on 2024-10-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_rename_first_prod_image_format_product_image_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_format',
            new_name='first_prod_image_format',
        ),
    ]
