# Generated by Django 5.0.6 on 2024-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rename_image_format_product_first_prod_image_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='image_format',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
