# Generated by Django 5.0.6 on 2024-10-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_commodity_image_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='change_by_ml',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
