# Generated by Django 5.0.6 on 2024-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0046_notification_change_by_ml'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('standard', 'Standard Perm'), ('unlimited', 'Unlimited Perm')]},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['standard', 'unlimited'], 'content_type__app_label': 'main'}, to='auth.permission'),
        ),
    ]
