# Generated by Django 5.0.6 on 2024-10-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_product_ago_1y_product_ago_2y_product_ago_5y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='increasefromlastyear',
        ),
    ]
