# Generated by Django 5.0.6 on 2024-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_product_increasefromlastyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='increasefromlastyear',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
