name: 1 - Hello World Github actions


on:
  workflow_dispatch:
  push: # git push
    branch:
      - main

jobs:
  hello:
    runs-on: ubunto-latest
    steps:
      - name: Hello there
        run: echo "hello"